IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Player'))
BEGIN
	CREATE TABLE [dbo].[Player](
		[IdPlayer] [bigint] IDENTITY(1,1) NOT NULL,
		[SkillPoints] [int] NOT NULL,
		[Gender] [int] NOT NULL,
		[Name] [nvarchar](50) NOT NULL,
		CONSTRAINT [PK_Player] PRIMARY KEY CLUSTERED ([IdPlayer] ASC)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) 
		ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SkillType'))
BEGIN
	CREATE TABLE [dbo].[SkillType](
		[IdSkillType] [bigint] IDENTITY(1,1) NOT NULL,
		[Description] [nvarchar](50) NOT NULL,
		[GenderAdventage] [int] NOT NULL,
		CONSTRAINT [PK_SkillType] PRIMARY KEY CLUSTERED ([IdSkillType] ASC)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) 
		ON [PRIMARY]
	) ON [PRIMARY]
END
GO

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SkillType'))
BEGIN
	INSERT INTO [dbo].[SkillType] ([Description], [GenderAdventage]) 
	VALUES 
	('Fuerza', 1),
	('Velocidad', 1),
	('Tiempo de reaccion', 2),
	('Carisma', 0),
	('Equilibrio', 0),
	('Flexibilidad', 0);
END
GO

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Skill'))
BEGIN
	CREATE TABLE [dbo].[Skill](
		[IdSkill] [bigint] IDENTITY(1,1) NOT NULL,
		[Value] [int] NOT NULL,
		[IdPlayer] [bigint] NOT NULL,
		[IdType] [bigint] NOT NULL
		CONSTRAINT [PK_Skill] PRIMARY KEY CLUSTERED ([IdSkill] ASC)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) 
		ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].[Skill] WITH CHECK ADD CONSTRAINT [FK_Skill_Player] FOREIGN KEY([IdPlayer]) REFERENCES [dbo].[Player] ([IdPlayer])
	ALTER TABLE [dbo].[Skill] WITH CHECK ADD CONSTRAINT [FK_Skill_SkillType] FOREIGN KEY([IdType]) REFERENCES [dbo].[SkillType] ([IdSkillType])
END
GO

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Tournament'))
BEGIN
	CREATE TABLE [dbo].[Tournament](
		[IdTournament] [bigint] IDENTITY(1,1) NOT NULL,
		[Date] [datetime] NOT NULL,
		[IdWinner] [bigint] NOT NULL,
		[Gender] [int] NULL,
		CONSTRAINT [PK_Tournament] PRIMARY KEY CLUSTERED ([IdTournament] ASC)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) 
		ON [PRIMARY]
	) ON [PRIMARY]		

	ALTER TABLE [dbo].[Tournament] WITH CHECK ADD CONSTRAINT [FK_Tournament_Winner] FOREIGN KEY([IdWinner]) REFERENCES [dbo].[Player] ([IdPlayer])
END
GO

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Match'))
BEGIN
	CREATE TABLE [dbo].[Match](
		[IdMatch] [bigint] IDENTITY(1,1) NOT NULL,
		[IdPlayer1] [bigint] NOT NULL,
		[IdPlayer2] [bigint] NOT NULL,
		[IdWinner] [bigint] NOT NULL,
		[Stage] [int] NULL,
		[IdTournament] [bigint] NULL
		CONSTRAINT [PK_Match] PRIMARY KEY CLUSTERED ([IdMatch] ASC)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) 
		ON [PRIMARY]
	) ON [PRIMARY]		

	ALTER TABLE [dbo].[Match] WITH CHECK ADD CONSTRAINT [FK_Match_Player1] FOREIGN KEY([IdPlayer1]) REFERENCES [dbo].[Player] ([IdPlayer])
	ALTER TABLE [dbo].[Match] WITH CHECK ADD CONSTRAINT [FK_Match_Player2] FOREIGN KEY([IdPlayer2]) REFERENCES [dbo].[Player] ([IdPlayer])
	ALTER TABLE [dbo].[Match] WITH CHECK ADD CONSTRAINT [FK_Match_Winner] FOREIGN KEY([IdWinner]) REFERENCES [dbo].[Player] ([IdPlayer])
	ALTER TABLE [dbo].[Match] WITH CHECK ADD CONSTRAINT [FK_Match_Tournament] FOREIGN KEY([IdTournament]) REFERENCES [dbo].[Tournament] ([IdTournament])
END
GO
